version: '3.7'
services:
  rp:
    environment:
    - RP_BACKEND=http://example.com
    #- RP_DOMAIN_NAME=rp.pulipuli.info
    ports:
    # - 80:80
    # - 443:443
    - 8080:80
    - 8443:443
    restart: unless-stopped
    build: .
    volumes:
    - ./conf/nginx/nginx-http.conf:/etc/nginx/nginx-http-template.conf
    - ./conf/nginx/nginx-https.conf:/etc/nginx/nginx-https-template.conf
    - ./nginx/cache:/tmp/nginx/cache
    - ./conf/certbot/conf:/etc/letsencrypt
    - ./conf/certbot/www:/var/www/certbot
    - ./build/cronjob:/etc/cron.d/cronjob