version: '3.7'
services:
  rp:
    environment:
    # Example
    #- RP_BACKEND=test-a.pulipuli.info,http://example.com|test-b.pulipuli.info,http://www.helloworld.org
    - RP_BACKEND=test-a.pulipuli.info,http://example.com|test-b.pulipuli.info,http://www.helloworld.org
    #- RP_DOMAIN_NAME=rp.pulipuli.info
    ports:
    - 80:80
    - 443:443
    # - 8080:80
    # - 8443:443
    #network_mode: host
    restart: unless-stopped
    build: .
    volumes:
    - ./conf/nginx/http-server.template:/opt/rp/nginx/rp/http-server.template
    - ./conf/nginx/https-server.template:/opt/rp/nginx/rp/https-server.template
    - ./conf/nginx/conf.template:/opt/rp/nginx/rp/conf.template
    - ./cache:/tmp/nginx/cache
    - ./conf/certbot/conf:/etc/letsencrypt
    - ./conf/certbot/www:/var/www/certbot